Affected Issue(s): Dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

What this commit has achieved:
1. The conflict is caused by:
    The user requested google-api-core==2.11.0
    google-cloud-bigquery 3.26.0 depends on google-api-core<3.0.0dev and >=2.11.1